In [1]:
import numpy as np
from numpy.fft import fft, ifft
np.set_printoptions(precision=6)

# Test: Correlation Real

In [77]:
x = np.asarray([2, 3])
e = np.asarray([5, 4])
np.correlate(x, e)

array([22])

In [78]:
x = np.asarray([1, 2])
e = np.asarray([5, 4])
np.correlate(x, e)

array([13])

In [74]:
x_block = np.asarray([6, 1, 2, 3])
e_block = np.asarray([0, 0, 5, 4])
ifft(np.conj(fft(x_block)) * fft(e_block))

array([ 22.+0.j,  13.+0.j,  34.+0.j,  39.+0.j])

# Test: Correlation Complex

In [91]:
x = np.asarray([2+1j, 3-2j])
e = np.asarray([5j, 4])
np.correlate(x, e, 'valid')

array([ 17.-18.j])

In [92]:
x = np.asarray([1+1j, 2+1j])
e = np.asarray([5j, 4])
np.correlate(x, e, 'valid')

array([ 13.-1.j])

In [93]:
x_block = np.asarray([6, 1+1j, 2+1j, 3-2j])
e_block = np.asarray([0, 0, 5j, 4])
np.conj(ifft(np.conj(fft(x_block)) * fft(e_block)))

array([ 17.-18.j,  13. -1.j,   4.-26.j,  14.-15.j])

# Test: Filter Real

In [104]:
x = np.asarray([1, 2])
w = np.asarray([2, 1])
np.convolve(x, w, 'valid')

array([5])

In [103]:
x = np.asarray([2, 3])
w = np.asarray([2, 1])
np.convolve(x, w, 'valid')

array([8])

In [109]:
x_block = np.asarray([6, 1, 2, 3])
w_block = np.asarray([2, 1, 0, 0])
ifft(fft(x_block) * fft(w_block))

array([ 15.+0.j,   8.+0.j,   5.+0.j,   8.+0.j])

# Test: Filter Complex

In [110]:
x = np.asarray([1+1j, 2+1j])
w = np.asarray([2j, 1])
np.convolve(x, w, 'valid')

array([-1.+5.j])

In [111]:
x = np.asarray([2+1j, 3-2j])
w = np.asarray([2j, 1])
np.convolve(x, w, 'valid')

array([ 6.+7.j])

In [112]:
x_block = np.asarray([6, 1+1j, 2+1j, 3-2j])
w_block = np.asarray([2j, 1, 0, 0])
ifft(fft(x_block) * fft(w_block))

array([ 3.+10.j,  4. +2.j, -1. +5.j,  6. +7.j])